/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DLL;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions.*;

class DLLTest {
    @Test
    void addHeadWorks() {
        main.java.DLL.DLL<Integer> dll = new main.java.DLL.DLL<Integer>();
        dll.linkHead(1);

        assertEqual(1, dll.unlinkHead());

        //Library classUnderTest = new Library();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
